### ISSUE TITLE
there is lack of some score data in downloaded midi

### ISSUE THREAD

**Issue by umjammer** [LibreScore/dl-librescore#17]
i've downloaded https://musescore.com/user/7281471/scores/10054033 as midi and pdf.
comparing those two scores, the downloaded midi is missing pedal, accent, cresc., dim., slur etc.
is it fixable?

[v0.34.45](https://github.com/LibreScore/dl-librescore/releases/download/v0.34.45/dl-librescore.user.js)
via Userscript of Tampermonkey on Mac Chrome

**Comment by sealsrock12** [comment]
This is probably because the midi format is quite limited, and only supports [a few commands](https://computermusicresource.com/MIDI.Commands.html). For example, an accent probably would have to be notated as a sharp increase and decrease in velocity. MuseScore either doesn't export that information in midi's (you can test this by creating a score with these details in the MuseScore desktop app and exporting it), or whatever you're using to view them can't decipher it. You would want MSCZ or MusicXML for full details.

In any case, we get the midi's directly from the musescore website with no processing, there isn't really anything we can do.

**Comment by umjammer** [comment]
do you mean there is lack of info on the web score data
because of musescore doesn't export everything?

---

but listening following two scores by the web player,

* w/o pedal
https://musescore.com/user/37832132/scores/9285043

* w/ pedal
https://musescore.com/user/7281471/scores/10054033

i can hear pedaled sound from the latter.
so at least there is pedal info on the web data.
but pedal info is disappeared in the downloaded midi.

this means that this program cannot detect the pedal info, right?

**Comment by sealsrock12** [comment]
No, the web player just plays an mp3 which is generated by musescore. If you download the mp3 from this tool, you will get the same results. As I said earlier, we get the midi/mp3 files directly from musescore.
