### ISSUE TITLE
librescore as a library

### ISSUE THREAD

**Issue by arashi-dev** [LibreScore/dl-librescore#28]
It would be great if we had the librescore as a library, so we are able to import it in our project and use it or wrap some ideas around it. any thoughts? 🤔

**Comment by PeterNjeim** [comment]
dl-librescore is a downloader tool, currently as a browser extension and as a CLI. I'm not sure what you'd need it as a library for other than making a GUI for it, in which case the browser extension is already a GUI and the CLI can be replaced with the open source MuseScore desktop app. If you have any ideas you can share them, but it seems this issue is more of a discussion starter, in which case it should be moved to the Discussions tab

**Comment by arashi-dev** [comment]
I had an idea to create a telegram bot for my friends and wrap some implementations and ideas that we had, around it to make our life easier.
for now, I used `child_process` to run `dl-librescore`'s package and save the file in a `tmp` folder, and then finally, send it to the user.
it's not really serious. I just thought maybe it was worth opening an issue to talk about.
if you think it is unnecessary, I'm okay with that :)

**Comment by PeterNjeim** [comment]
PR's are welcome. All the LibreScore devs including myself have stopped working on the project so we won't be writing any more code except for bug fixes lol, sorry my guy

**Comment by arashi-dev** [comment]
makes sense :)
thanks for the response anyway

**Comment by TheAfroOfDoom** [comment]
@arashi-dev is this something you're still interested in?

**Comment by arashi-dev** [comment]
@TheAfroOfDoom Using the cli script inside my js code did the job for me. So, implementing it is not necessary for me anymore
