### ISSUE TITLE
PDF print size issue 

### ISSUE THREAD

**Issue by developerfox1** [LibreScore/dl-librescore#7]
After downloading the PDF from the terminal, There is a problem with the print size of the PDF, it's like 1/4 of the bond paper. I'm not sure but there might be artifacts generated outside of the PDF.

**Comment by developerfox1** [comment]
![issue](https://user-images.githubusercontent.com/91423599/189894230-afcdae2d-3599-4ae8-86f7-99516ea7f202.png)

It happens on every score.

**Comment by PeterNjeim** [comment]
The song you downloaded is probably in Letter or A4 and is working as expected. Your print size is probably a non-standard size. If you want to change the score so that it fits to your desired dimensions, download the MSCZ file of the song with the LibreScore App, and use the MuseScore desktop program to change the sheet dimensions.

**Comment by developerfox1** [comment]
> The song you downloaded is probably in Letter or A4 and is working as expected. Your print size is probably a non-standard size. If you want to change the score so that it fits to your desired dimensions, download the MSCZ file of the song with the LibreScore App, and use the MuseScore desktop program to change the sheet dimensions.

It's on A4, I already tried it on my other devices. But I haven't tried it on MuseScore program, I'll give it a try.

**Comment by Xmader** [comment]
@developerfox1 Have you tried to open it in another PDF reader on the same device?

**Comment by Xmader** [comment]
Probably an error in [PDF processing](https://github.com/LibreScore/dl-librescore/blob/master/src/pdf.ts).

**Comment by PeterNjeim** [comment]
I don't think so, every PDF has worked for every score I've ever tried (and for everyone else as well). Even the thumbnail preview is correct: 
![image](https://user-images.githubusercontent.com/26418974/222007852-450aae1a-688c-4113-aace-f35219d4a631.png)
so I doubt it has anything to do with dl-librescore, which is why I closed it. The easiest way to check for sure is to download the same score. Here it is: https://musescore.com/classicman/scores/62312
![image](https://user-images.githubusercontent.com/26418974/222008134-48bdca37-cdcb-4a6c-9678-60c4256e3072.png)
Works just fine. At a 10% scale I get something similar:
![image](https://user-images.githubusercontent.com/26418974/222008265-a4acda5a-60bf-4ec8-8ad3-856709ca5182.png)
so probably just missing a 0 at the end of his scale number
