### ISSUE TITLE
Userscript will not download pdf 

### ISSUE THREAD

**Issue by Ryder2368** [LibreScore/dl-librescore#84]
The userscript on Android will not download pdf or midi files on certain scores and for other score I can only download the first page. This has only changed since musescore was updated. Not sure what to do. I am using tamper monkey and have tried updating script but no use.

**Comment by PeterNjeim** [comment]
Please share details about what these "certain scores" are. If they are official scores, it is because official scores are not supported

**Comment by DLeich** [comment]
For me, I'm not seeing the download buttons anymore on any scores I go to with dl-librescore installed via tampermonkey in Chrome.  This seems to be new behavior around the last week I think.  Seeing this happen on two different computers, both running Ubuntu and Chrome.  For example, this score doesn't show the download buttons (it's an interactive, community score - not pro or 'official'):
https://musescore.com/user/16006641/scores/4197961

**Comment by Ryder2368** [comment]
No not an official score actually just test drive https://musescore.com/user/2466621/scores/1327981 and a version of the piano man https://musescore.com/user/2136241/scores/4650781 however it may just be my phone so I have been using the app. You know with the webmscore. This seems to be working so I might stick with that. Haven't tried any other scores with user script.

**Comment by PeterNjeim** [comment]
@Ryder2368 both of those are working for me on Firefox Android. Maybe try enabling desktop mode?

**Comment by PeterNjeim** [comment]
@DLeich working for me, can you see if it works when enabling desktop mode?

**Comment by PeterNjeim** [comment]
@DLeich it might be MuseScore doing an A/B test on their website, and that's why it's working on one browser and not the other. I'll look into it. In the meantime, you can always download by using the download buttons in the Tampermonkey menu. Go to a song on musescore.com, then click on the Tampermonkey extension icon in your browser's top bar, and you'll see the download buttons there

**Comment by DLeich** [comment]
Okay my issue is resolved.  It was entirely on my end - the developer settings for the chrome extension somehow was disabled for me.  Once I enabled it, the buttons showed again.

I also think I know what's going on with @Ryder2368 's issue.  I also noticed that many pdf arrangements, published through Hal Leonard, were not downloading.  I even reached out to MuseScore support about this since I'm paying for the subscription.  Many of the arrangements no longer have a PDF download option because of copyright restrictions - I imagine that this is preventing dl-librescore from scraping for PDFs as well.

**Comment by PeterNjeim** [comment]
Hal Leonard and Faber scores are what are called "official scores". These are not supported and I mentioned this in an earlier reply. I'm still waiting for a response to confirm

**Comment by Ryder2368** [comment]
Yes thank you I updated Firefox like twice and enabled desktop site and it is now working. Thanks a lot you guys are legends. Also I updated the user script which might have fixed it.

**Comment by Ryder2368** [comment]
Also noticed that my phone wouldn't download the MP3 versions for the app but would with user script. However this isn't a problem. I believe that this issue is fixed.
